CREATE TABLE Roles (
    RoleID  SERIAL PRIMARY KEY,
    RoleName VARCHAR(50) NOT NULL
);

INSERT INTO Roles (RoleName) VALUES ('Admin');
INSERT INTO Roles (RoleName) VALUES ('User');

CREATE TABLE Permissions (
    PermissionID  SERIAL PRIMARY KEY,
    PermissionType VARCHAR(20) NOT NULL,
    RoleID INT,
    FOREIGN KEY (RoleID) REFERENCES Roles(RoleID) ON DELETE CASCADE
);

CREATE TABLE Users (
    UserID  SERIAL PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    RoleID INT,
    FOREIGN KEY (RoleID) REFERENCES Roles(RoleID) ON DELETE SET NULL
);
